# 코퍼스(말뭉치) 수집

- 데이터를 제공받는다, 크롤링등을 통해서 수집한다
- 데이터 수집 단계와 동일
- 데이터
  - 단일 언어 코퍼스 (한개 언어로만 구성)
  - 이중 언어 코퍼스 (2개 언어로만 구성)
  - 다중 언어 코퍼스 (2개이상 언어로 구성)
  - 병렬 언어 코퍼스 (여러개의 언어가 쌍으로(대칭적으로) 구성)

# 정제

- 전각 문자(특수문자표..) 제거 (검토, ,.?!등은 고려)
- 대소문자 통일(알파벳기반)
- 정규식을 이용(노이즈 제거)

# 문장 단위 분절
- 하나의 문장은(문장의 끝은 .) 재료에 따라 다양하게 존재한다
  - 하나의 문장이 여러줄에 걸쳐있다
  - 한줄에 여러문장이 존재한다  
  => 이런 재료를 한줄에 한문장으로 구성되게 조정

In [0]:
# 설치
#! pip install nltk

In [0]:
import nltk

In [0]:
# 한줄에 여러문장, 여러줄
src_text = '''초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다. 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.
초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다. 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.

'''
print( '[%s]' % src_text )

[초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다. 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.
초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다. 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.

]


In [0]:
# 작업 편의상 파일에 기록했다
with open('test.txt','w') as f:
  f.write( src_text )

In [0]:
# 문장의 토큰화처리
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [0]:
# 한글의 경우 정형화된 문서(법률, 소설, 기사 등등은 쉼표, 마침표를 잘 찍어서 표현)이외에
# 대화체(sns, 채팅등 문서)는 누락이 많아서 크게 효과는 못 얻을수 있다. 
# 단, sns, 채팅 => 한 문장 단위로 끊어치는 성향이 강해서 그 기준으로 분류해도 좋다
with open('test.txt','r') as f:
  for line in f:
    msg = line.strip()# 한줄씩 공백제거해서 획득
    #print(msg)
    if msg:
      sentences = sent_tokenize( msg ) # 한줄에 대한 문장을 추출 
      for s in sentences: # 문장별로 출력
        if s:
          print( s )

초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다.
그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다.
인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다.
대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.
초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다.
그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에 대한 고려를 하지 못한 것 같다.
인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다.
대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.


In [0]:
# 한문장에 여러줄에 걸쳐서 표현되어 있다
src_text = '''초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 
제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 
그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에
 대한 고려를 하지 못한 것 같다. 
 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 
 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 
 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.
'''
print( '[%s]' % src_text )

with open('test2.txt','w') as f:
  f.write( src_text )

[초기 인공지능 연구에 대한 대표적인 정의는 다트머스 회의에서 존 매카시가 
제안한 것으로 "기계를 인간 행동의 지식에서와 같이 행동하게 만드는 것"이다. 
그러나 이 정의는 범용인공지능(AGI, 강한 인공지능)에
 대한 고려를 하지 못한 것 같다. 
 인공지능의 또다른 정의는 인공적인 장치들이 가지는 지능이다. 
 대부분 정의들이 인간처럼 사고하는 시스템, 인간처럼 행동하는 시스템, 
 이성적으로 사고하는 시스템 그리고 이성적으로 행동하는 시스템이라는 4개의 분류로 분류된다.
]


In [0]:
# 한 문장이 여러줄에 포함된 경우 => 한줄에 여러문장으로 처리하거나, 
# 마침표 기준으로 문자을 나누던가 처리가 필요
buffer = []
with open('test2.txt','r') as f:
  for line in f:
    msg = line.strip()
    buffer += [ msg ]
    tmp = ' '.join( buffer )
    # 여러줄에 걸친 문장을 한줄로 다시 합치기
msg = ' '.join(buffer)
# msg를 다시 위에서 처럼 한문장씩 빼주면 처리가 가능

# 분절

- 형태소 분석, 단순 분석등 정규화 수행
- Mecab을 많이 사용

In [0]:
# 영어 문장의 경우  => 띠어쓰기 기준으로 토큰화 처리가 가능
# 방법1 spacy
import spacy

In [0]:
# 재료
en_txt = 'Abby is an American sitcom created by Nat Bernstein and Michael Katlin that aired for one season on UPN from January 6, 2003, to March 4, 2003.'
en_txt
spacy_en = spacy.load('en')

In [0]:
# 띠어쓰기 기준으로 토큰화, 각주(, .)등도 토큰화를 처리했다
print( [ token for token in spacy_en.tokenizer( en_txt ) ] )

[Abby, is, an, American, sitcom, created, by, Nat, Bernstein, and, Michael, Katlin, that, aired, for, one, season, on, UPN, from, January, 6, ,, 2003, ,, to, March, 4, ,, 2003, .]


In [0]:
# 방법2 nltk
import nltk
from nltk.tokenize import word_tokenize

print( word_tokenize(en_txt) )

['Abby', 'is', 'an', 'American', 'sitcom', 'created', 'by', 'Nat', 'Bernstein', 'and', 'Michael', 'Katlin', 'that', 'aired', 'for', 'one', 'season', 'on', 'UPN', 'from', 'January', '6', ',', '2003', ',', 'to', 'March', '4', ',', '2003', '.']


In [0]:
from IPython.display import Image
Image('/content/분절.png', width=500)

## Mecab
- 일본어 형태소 분석용 오픈소스로 개발된 소스를 한국어에 맞게 wraping해서 제공
- 한글 분절용으로 대표적으로 가장 많이 사용
- '은전한닢'이라는 내용을 처음으로 적용하서 한국어 기능이 추가되었다(Mecab Fork 프로젝트)

## 설치
- konlpy
- open jdk
- Mecab 소스 다운로드 빛 컴파일(make)
- Mecab-ko 설치
- Mecab-ko-dic 설치
- Mecab 설치
- 설치후 , 런타임이 종료되면 => 사용않됨  
  오랜 사용으로 메모리가 꼬여서 사용안될수도 있다
  => 런타임 초기화후 => 설치 => 사용
  

In [0]:
# konlpy 설치
!pip install konlpy

     |████████████████████████████████| 19.4MB 1.3MB/s 
     |████████████████████████████████| 92kB 8.6MB/s 
     |████████████████████████████████| 2.3MB 43.7MB/s 
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [0]:
# jdk 설치
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!pip3 install JPype1-py3

     |████████████████████████████████| 92kB 2.7MB/s 
  Created wheel for JPype1-py3: filename=JPype1_py3-0.5.5.4-cp36-cp36m-linux_x86_64.whl size=2677226 sha256=89aac600186ef6073adbeb41c05c1149081af257e57487abd6d29894260ba714
  Stored in directory: /root/.cache/pip/wheels/52/37/1f/1015d908d12a0e9b239543d031fda0cded9823aa1306939541
Successfully built JPype1-py3


In [0]:
'''
셀스크립트로 설치하는 방법
! bash <(curl -s https://.../mecab.sh)
'''
! bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

In [0]:
import os
os.chdir('/tmp/')
!curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.1.tar.gz
!tar zxfv mecab-0.996-ko-0.9.1.tar.gz
os.chdir('/tmp/mecab-0.996-ko-0.9.1')
!./configure
!make
!make check
!make install


In [0]:
import os
os.chdir('/tmp')
!curl -LO https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.0.1-20150920.tar.gz
!tar -zxvf mecab-ko-dic-2.0.1-20150920.tar.gz
os.chdir('/tmp/mecab-ko-dic-2.0.1-20150920')
!./autogen.sh
!./configure
!make
# !sh -c 'echo "dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic" > /usr/local/etc/mecabrc'
!make install

In [0]:
# install mecab-python
import os
os.chdir('/content')

!git clone https://bitbucket.org/eunjeon/mecab-python-0.996.git
os.chdir('/content/mecab-python-0.996')

!python3 setup.py build
!python3 setup.py install

In [0]:
# 한글은 띠어쓰기를 수행하면, 토큰화 처리시 단어수가 너무 많아진다 => 형태소 단위로 진행
# 띠어쓰기도 잘 이행하지 않고, 100% 아직 정형화가 않되 있어서 사용 X
from konlpy.tag import Mecab

In [0]:
# 재료
ko_sentence = '오늘 점심 무엇을 먹을까'
# 형태소 분석기
# Mecab의 성분(태그표) = bit.ly/2StqivH
tokenizer   = Mecab()
# morphs
print( tokenizer.morphs(ko_sentence) )

['오늘', '점심', '무엇', '을', '먹', '을까']


In [0]:
# pos함수로 품사 태깅 수행
tokens = tokenizer.pos(  ko_sentence )
print( tokens )

[('오늘', 'MAG'), ('점심', 'NNG'), ('무엇', 'NP'), ('을', 'JKO'), ('먹', 'VV'), ('을까', 'EC')]


In [0]:
tokenizer.tagset.get( 'MAG' )

'일반 부사'

In [0]:
print( [ ( k , tokenizer.tagset.get( v ) ) for k,v in tokens  ] )

[('오늘', '일반 부사'), ('점심', '일반 명사'), ('무엇', '대명사'), ('을', '목적격 조사'), ('먹', '동사'), ('을까', '연결 어미')]


## Moses
- 영어 분절용, 띠어쓰기 문제점은 않가지고 있다
- 쉼표, 마침표, 인용부호은 띠어 쓰기 처리 필요


In [0]:
nltk.download('perluniprops')
from nltk.tokenize.moses import MosesTokenizer

[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Unzipping misc/perluniprops.zip.


In [0]:
en_str = '''According to the Book of Exodus, Moses was born in a time when his people, the Israelites, an enslaved minority, were increasing in population and, as a result, the Egyptian Pharaoh worried that they might ally themselves with Egypt's enemies.
'''
en_str

"According to the Book of Exodus, Moses was born in a time when his people, the Israelites, an enslaved minority, were increasing in population and, as a result, the Egyptian Pharaoh worried that they might ally themselves with Egypt's enemies.\n"

In [0]:
nltk.download('nonbreaking_prefixes')
t = MosesTokenizer()

[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping corpora/nonbreaking_prefixes.zip.


In [0]:
tmp = t.tokenize( en_str.strip() )
print( tmp )

['According', 'to', 'the', 'Book', 'of', 'Exodus', ',', 'Moses', 'was', 'born', 'in', 'a', 'time', 'when', 'his', 'people', ',', 'the', 'Israelites', ',', 'an', 'enslaved', 'minority', ',', 'were', 'increasing', 'in', 'population', 'and', ',', 'as', 'a', 'result', ',', 'the', 'Egyptian', 'Pharaoh', 'worried', 'that', 'they', 'might', 'ally', 'themselves', 'with', 'Egypt', '&apos;s', 'enemies', '.']


## 서브워드 분절
- BPE 알고리즘 사용
- 좀더 작은 단위의 서브워드로 분절
  - 전제 : 단어는 의미를 가진 더 작은 서브워드들의 조합으로 이루어진다
    - 한국어 : 집중, 정문,.. => 集(모을집) + 中(가운데중)
    - 영어 : concentrate => con + cent + rate
  - 적용
    - 신경망 => 신경 + 망
    - 중국어 => 중국 + 어    

## 병렬 코퍼스 분절

- 여러 문장 단위로 분절

# 사전(단어장, voca..)생성

## 개요
- 페이스북에 MUSE에서는 사전 구축 방법을 코드와 함께 제공 
- 언어별로 단어가 많이 사용되거나 하면, 사전이 필수적으로 필요하게 된다
- 해당 코퍼스를 기준으로 형태소를 뽑아내면(분절) 하면 이를 사전(단어장으로 )으로 구성할수 있다.
  - 특정 형태소에 대해 인덱스가 부여가 되고
  - 그 인덱스를 기준으로 백터화를 수행할수 있다
  - 단어 임베딩 처리를 통해서 인공신경망에서 훈련할수 있는 데이터화 처리가 완성된다

## 단어장 생성 방식
- 중복되지 않는 토큰(고유하다, 사전내에서는)
- 해당 토큰에 고유한 숫자를 부여(인덱스)
- 샘플 데이터는 네이버 감성 영화 코퍼스 데이터사용
  - https://github.com/e9t/nsmc => ratings.txt 업로드
  - 컬럼 3개 : id	document	label
  - label은 1이면 긍정, 0이면 부정

In [0]:
# step 1 : 코퍼스 수집(git를 통해서 네이버 감성 영화 코퍼스 자료 획득)
# step 2 : 분절용 한글 처리 형태소 분석기(분절 세부 과정은 통으로 분절이라고 표현)
from konlpy.tag import Mecab
tokenizer = Mecab()

In [0]:
# step 3 : 사전, 단어장 만들기
# 3-1. 파일을 읽는다
with open('/content/ratings.txt') as f:
  # 3-2. 내용을 이미 한줄로 되어서 문장 단위 분절은 필요 없고, 바로 라인별로 분해->id는 누락
  # 컬럼 파트는 빼고 사용
  raw = f.read().splitlines()[1:]
  print( len(raw), raw[:3] )
  # 데이터 한개는 \t 으로 구분되어 있다
  # => [ [ '어릴때보고 ..', '1' ], [], .... ]
  #data = [ lineStr.split('\t')[1:] for lineStr in raw ]
  data = list( map( lambda x : x.split('\t')[1:], raw ) )
  print( data[:2] )
  # 3-3. 토큰화처리, 분절처리 => morphs()
  # [ (['','',''], 1),(), (), ... ]
  # x => ['어릴때보고 지금다시봐도 재밌어요ㅋㅋ', '1']
  # x[1] => 1
  # x[0] => '어릴때보고 지금다시봐도 재밌어요ㅋㅋ'
  data = list( map( lambda x :( tokenizer.morphs(x[0]), x[1]), data ) )
  print( data[:2] )

200000 ['8112052\t어릴때보고 지금다시봐도 재밌어요ㅋㅋ\t1', '8132799\t디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업이 부러웠는데. 사실 우리나라에서도 그 어려운시절에 끝까지 열정을 지킨 노라노 같은 전통이있어 저와 같은 사람들이 꿈을 꾸고 이뤄나갈 수 있다는 것에 감사합니다.\t1', '4655635\t폴리스스토리 시리즈는 1부터 뉴까지 버릴께 하나도 없음.. 최고.\t1']
[['어릴때보고 지금다시봐도 재밌어요ㅋㅋ', '1'], ['디자인을 배우는 학생으로, 외국디자이너와 그들이 일군 전통을 통해 발전해가는 문화산업이 부러웠는데. 사실 우리나라에서도 그 어려운시절에 끝까지 열정을 지킨 노라노 같은 전통이있어 저와 같은 사람들이 꿈을 꾸고 이뤄나갈 수 있다는 것에 감사합니다.', '1']]
[(['어릴', '때', '보', '고', '지금', '다시', '봐도', '재밌', '어요', 'ㅋㅋ'], '1'), (['디자인', '을', '배우', '는', '학생', '으로', ',', '외국', '디자이너', '와', '그', '들', '이', '일군', '전통', '을', '통해', '발전', '해', '가', '는', '문화', '산업', '이', '부러웠', '는데', '.', '사실', '우리', '나라', '에서', '도', '그', '어려운', '시절', '에', '끝', '까지', '열정', '을', '지킨', '노라노', '같', '은', '전통', '이', '있', '어', '저', '와', '같', '은', '사람', '들', '이', '꿈', '을', '꾸', '고', '이뤄나갈', '수', '있', '다는', '것', '에', '감사', '합니다', '.'], '1')]


In [0]:
# 데이터가 너무 많으니까, 샘플링을 해서 진행
# 긍정 : 1, 부정 : 0 
# 긍정 리뷰 10개, 부정 리뷰 10개를 샘플링
sampling_data = data[5:5+10] +  data[-10:]
print( sampling_data[0], sampling_data[-1] )

(['사랑', '을', '해', '본', '사람', '이', '라면', '처음', '부터', '끝', '까지', '웃', '을', '수', '있', '는', '영화'], '1') (['포', '풍', '저그', '가', '나가', '신다', '영차영차', '영차'], '0')


In [0]:
# 리스트 구성원의 순서끼리 묶어서(같은 성분끼리 묶어서) 데이터를 구성
# zip(*시퀀스데이터)
# [ ([],[],[],), (1,1,1,.. 0,0,0) ]
print( list(zip( *sampling_data )) )
tmp = list(zip( *sampling_data ))

[(['사랑', '을', '해', '본', '사람', '이', '라면', '처음', '부터', '끝', '까지', '웃', '을', '수', '있', '는', '영화'], ['완전', '감동', '입니다', '다시', '봐도', '감동'], ['개', '들', '의', '전쟁', '2', '나오', '나요', '?', '나오', '면', '1', '빠', '로', '보', '고', '싶', '음'], ['굿'], ['바보', '가', '아니', '라', '병', '쉰', '인', '듯'], ['내', '나이', '와', '같', '은', '영화', '를', '지금', '본', '나', '는', '감동', '적', '이', '다', '.', '.', '하지만', '훗날', '다시', '보', '면', '대사', '하나하나', '그', '감정', '을', '완벽', '하', '게', '이해', '할', '것', '만', '같', '다', '.', '..'], ['재밌', '다'], ['고질라', '니무', '귀엽', '다', '능', 'ㅋㅋ'], ['영화', '의', '오페라', '화', '라고', '해야', '할', '작품', '.', '극단', '적', '평갈', '림', '은', '어쩔', '수', '없', '는', '듯', '.'], ['3', '도', '반전', '좋', '았', '제', '^^'], ['장르', '는', '무협', '인데', '내', '가', '보', '기', '엔', '코믹', '이', '던데', '막장', '평점', '2', '점', '도', '아깝', '다'], ['나치', '입장', '에서', '본', '영화', '가', '갑자기', '연속', '으로', '나오', '네', '?', '뭔일', '있', '었', '나', '.', '..'], ['태권도', '?', '??'], ['음', '왜', '봤', '을까', '?', '예고편', '이', '다', '-'], ['개연', '성', '이', '없', '어요', '.', '.',

In [0]:
# 테스트 토큰화된 데이터만 
print( tmp[0][0] )

['사랑', '을', '해', '본', '사람', '이', '라면', '처음', '부터', '끝', '까지', '웃', '을', '수', '있', '는', '영화']


In [0]:
# 사전화 작업은 토큰을 => 고유번호 대입
# 전체 데이터를 돌면서 => 하나의 리뷰를 획득 
# => 하나의 토큰을 획득 => 사전에 있었는지 체크 => 없었다면(신규단어) => 새로운 인덱스를 부여
# => 새로운 인덱스는 어떻게 계산? 딕셔너리(사전의 자료구조)에 길이값으로 세팅하겟다
# 사전


In [0]:
# 전체 데이터 
len(tmp[0])
vocab = dict() # { '토큰':인덱스 }
# 추가부분 
# 단어장에 없는 형태소가 있는 경우 : unknow
# 문장의 크기를 맞출때 필요할경우 문장의 길이를 동일하게 처리하기 위해 padding 추가
# 토치텍스트에서 시퀀스 구성후 문장 임베딩될때 삽입되는 기호와 동일하게 구성
# <unk>:0, <pad>:1
vocab['<unk>'] = 0
vocab['<pad>'] = 1
for sentence in tmp[0]:  # 20문장을 반복하면서 한문장씩 뽑고
  #print( sentence )
  for token in sentence: # 한문장에서 형태소를 한개씩 뽑고
    #print( token )
    if not token in vocab:# 사전안에 해당 토큰이 등록되어 있는가?없다면
      #vocab[token] = len(vocab)
      vocab.setdefault( token, len(vocab) )# 사전에 형태소를 추가, 단 값은 사전의 현재 개수
len(vocab), vocab['-']

(155, 122)

# 단어 임베딩


## 수치화

In [0]:
# ( 한 문장에서 사용된 형태소가 모여있는 리스트, 사전)
def numericalize( sent, vocab ):
  # sent에서 토큰을 하나씩 꺼내서, 사전에 대조하여 인덱스(토큰의 인덱스값,특성값)를 구한다
  # '사랑' => 2번으로 표기
  tmp = list()
  for token in sent:   # 형태소 덩어리에서 한개의 토큰(형태소)를 추출
    # 해당 토큰이 사전에 존재하는가?
    if token in vocab: # 존재하면
      tmp.append( vocab[token] ) # '사랑' => 2
    else:              # 그런단어가 사전에 없다면
      tmp.append( vocab.get('<unk>') )
  return tmp

# [ ([1,2,3,..], 1), (), (), ...]
numericalize_data = [ ( numericalize( sent , vocab), label ) 
                      for sent, label in sampling_data        # 1. 문장(형태소처리된) 20개를 반복
                    ]
# 개별 확인
print(numericalize_data[-2])
print(sampling_data[-2])

([118, 139, 140, 115, 141, 142, 143, 35, 36, 55, 144, 145, 146, 147, 78], '0')
(['왜', '난', '재미없', '었', '지', 'ㅠㅠ', '라따뚜이', '보', '고', '나', '서', '스머프', '봐서', '그런가', 'ㅋㅋ'], '0')


In [0]:
len(vocab)

155

## 단어 주머니(Bag of Words)

- 고전 기법
- 단어의 출현빈도로만 문장별로 기록(순서는 미고려)
- 문서-단어의 행렬이라고 표현 : term-matrix
- 행렬 구성
  - 행:문장
  - 열:각 문장에서 사용된 고유 단어(형태소)의 각각의 개수가 표현

In [0]:
import torch
from collections import Counter

In [0]:
# 사용데이터는 numericalize_data를 사용한다 => 긍정 10, 부정10개의 문장
# 문서(장)의 개수 : 행
num_docs = len(numericalize_data)
num_docs

20

In [0]:
# 사전의 단어수 : 열
num_vocabs = len( vocab )  
num_vocabs

155

In [0]:
# 행렬 구성 => 초기값 0
term_matrix = torch.zeros( num_docs, num_vocabs )
term_matrix,term_matrix.size()

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]), torch.Size([20, 155]))

In [0]:
# numericalize_data을 반복 작업하면서, 원소들의 카운트를 처리
for sent, label in numericalize_data:
  print( sent )
  # 한 문장안에 특정 토큰이 몇번 나왔는가?
  #print( list(Counter(sent).items()) )
  # 각 자리 원소끼리 따로 묶어라 => zip(*시퀀스데이터)
  # Counter(sent) => { 1:1, 2:2, 3:1, 4:1 } => { 형태소1번(사전상의인덱스):1번등장,  }
  # Counter(sent).items() => [ (1, 1), (2, 2), (3, 1), ... ]
  tokens, cnts = zip(*list(Counter(sent).items()))
  # 문장안에 각 형태소와, 빈도를 가진 각각의 리스트를 획득
  # tokens => [ 1,2,3,4,.... ]
  # cnts   => [ 1, 2, 1, 1, ...]
  # 수치화된 토큰만
  print( tokens )
  # 빈도만
  print( cnts )
  break

NameError: ignored

In [0]:
#cnts

(1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [0]:
torch.FloatTensor(cnts), torch.FloatTensor(cnts).size()

(tensor([1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 torch.Size([16]))

In [0]:
# 사전의 인덳스는 정수니까, int계열
# 향후 데이터가 풀로 들어가면 사전의 수가 int값의 범위를 넘어설수도 있다
# long으로 처리해야 사전의 크기에 오류가 않생긴다> 전부다 표현할수 있다
torch.LongTensor(tokens), torch.LongTensor(tokens).size()

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
 torch.Size([16]))

In [0]:
# numericalize_data에서 문장 순서대로 데이터를 카운트 처리가 되므로
for i, (sent, label) in enumerate(numericalize_data):
  tokens, cnts = zip(*list(Counter(sent).items()))
  # term_matrix에 빈도 계산한것을 대입 => (20, 155)
  # 대입은 각 토큰에 위치에서 설정된다
  term_matrix[ i , torch.LongTensor(tokens) ] = torch.FloatTensor( cnts )
term_matrix[-1]
# 행은 문장 => 샘플문장이 20개 term_matrix[ i(i번째 문장), ]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
# 문제점 => 0이 너무 많다
term_matrix.eq(0).sum()

tensor(2882)

## 단어주머지 문제점
- 문장이 많으면 => 토큰수가 늘어나고 => 수치 백터의 차원이 커진다
  - 힙스의 법칙 (heaps laws)
  - 로그함수적으로 증가한다
- 차원이 크면 -> 특성을 표현하기가 어렵다 -> 차원의 저주 -> 데이터가 희소해진다 -> 0이 많아지고 -> 선형 결합(행렬의곱)에서 활성화 함수를 통과한 값도 0이 되고, 이를 미분(역전파)값도0이되고 -> 학습 성과가 저하 -> 단어 백터의 밀집화(dense) 필요


## padding

- 문장의 길이는 각각 다르기 때문에 항상 같은 깉이로 만들어줘야 효율이 좋다
- 문장의 최대 길이 기준으로 패딩 처리

In [0]:
# 샘플링 데이터 중에 가장 긴 문장의 길이 획득
max_len = max( [ len(문장) for (문장, _) in numericalize_data  ] )
max_len

38

In [0]:
for s,_ in numericalize_data:
  # 현재 문장의 길이가 최대 문장의 길이보다 작으면
  c_len = len(s)# 현재 문장의 길이
  if c_len < max_len:
    # padding 표현을 추가한다 => <pad>
    # [18, 19, 20, 21, 22, 19] => [18, 19, 20, 21, 22, 19, 1, 1, 1, 1, 1...... 1]
    s += [vocab['<pad>']] * (max_len - c_len)

print( numericalize_data[0] )
  

([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 3, 14, 15, 16, 17, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], '1')


# 분절의 복원[별도단계]

# 파이토치의 토치텍스트 라이브러리[별도]

- torchtext
- 자연어처리,텍스트를 이용한 머신러닝/딥러닝 수행
- 데이터 전처리 기능도 모두가지고 있다
- 자연어 처리 데이터 종류

|x|y|사용분야|
|--|--|--|
|코퍼스|클레스|텍스트 분류, 감성 분석|
|코퍼스|--|언어 모델|
|코퍼스|코퍼스|기계번역, 요약, QA(질의응답)|

- 위에서 진행한 전처리 과정은 토치텍스트를 이용해서 구현/해결이 가능하다
  - 필드 지정
  - 데이터 셋 만들기 
  - 단어장 생성
  - 데이터 로더 생성

In [0]:
# 자연어 처리를 하는데 (전처리 => 레이어설계 => 학습, 평가 => 결과물(번역,요약,분류,..))
# 엔진 : 파이토치
# 핵심모듈 : 토치텍스트
# 형태소 분석기 : Mecab
# 전처리 과정은 토치텍스트를 사용
from torchtext.data import Field
# 분절 처리를 하는 한글 형태소 분석기는 Mecab
from konlpy.tag import Mecab

## 필드 정의 (데이터들의 모양, 특성등등 정의)
- 텐서로 표현할수 있는 텍스트 데이터 타입
- 각 토큰을 숫자 인덱스 매핑해주는 단어장 객체도 포함
- 토큰화 처리
- 전처리, 후처리 다 지정할수 있다

In [0]:
tokenizer = Mecab()

In [0]:
# ratings.txt의 데이터를 들여다 보면 
# id, 리뷰내용, 긍정/부정
# 리뷰 내용에 대한 필드
'''
sequential : 이 필드가 다루는 데이터가 시퀀스 데이터인가? => 문장 => 시퀀스 데이터(문자열이기도하고)
use_vocab  : 사전을 사용할 것인가? True => 사전생성이 들어간다(형태소쪼개고, 인덱스로 사전구성)
tokenize   : 사전을 사용한다면, 형태소 분석기는, 혹은 토큰 분석기는 어떤것이 담당할것인가?
             기본값 : Spacy, 한국어 => tokenizer.morphs 를 사용
lower       : 소문자로 처리해서 사용할것인가? (대문자를 소문자로 처리하는 것이 영어권는 일반적) 
batch_first : True:[ batch, h, w ] 이런 배치 False:[ h, w, batch ]
'''
TEXT  = Field( sequential = True, # 시퀀스 데이터 맞다
               use_vocab  = True, # 사전을 사용하겟다
               tokenize   = tokenizer.morphs, # 행태소 분석기로 이 함수를 사용하겟다
               lower      = True, # 소문자로 처리하겟다
               batch_first= True  # 배치사이즈는 앞으로 위치  
)

# 긍정/부정에 대한 필드
# preprocessing : 전처리
LABEL = Field( sequential = False, # 0 or 1
               use_vocab  = False, # 사전 사용 안함
               batch_first= True,
               preprocessing = lambda x: int(x), # 정수 처리
               is_target  = True   # 타겟 데이터 맞음 => y    
)

# 리뷰의 순서에 대한 필드(단, 사용하지는 않을것이다)
# 데이터 로드시 받아 주긴 해야 하므로, 기본적인것만 설정
ID    = Field( sequential = False,
               use_vocab  = False,
               is_target  = False
              )

## 데이터 셋 만들기

In [0]:
from torchtext.data import TabularDataset
# TabularDataset
# 데이터를 불러와서 정의한 필드를 기준으로 데이터를 처리해주는 객체

In [0]:
# 데이터를 주입하기 위해서 데이터를 준비한다
dataset = TabularDataset( path='/content/ratings.txt', # 데이터 파일의 위치, 경로
                          format='tsv',       # tab으로 분리되어 있다 tsv, csv, json등이 가능
                          fields=[('id',ID),('text',TEXT),('label',LABEL)], # (필드를호출할 닉네임,필드)
                          skip_header=True    # 데이터의 첫줄은 생략
                         )
# 데이터를 읽어와서 정해준 규칙에 의해 전처리, 형태소분리등 처리하여 필드에 담는다

## 단어장 생성

In [0]:
# TEXT 필드에서 단어장(사전)을 생성
TEXT.build_vocab( dataset )

In [0]:
# 단어장의 형태소 개수
len(TEXT.vocab), type(TEXT.vocab), TEXT.vocab

(62531, torchtext.vocab.Vocab, <torchtext.vocab.Vocab at 0x7f59f5bf31d0>)

In [0]:
# 단어장 인덱스 확인
# 문자열(형태소) 넣어서 사전상의 인덱스를 구해라
TEXT.vocab.stoi['<unk>'], TEXT.vocab.stoi['<pad>'], TEXT.vocab.stoi['사랑'], type(TEXT.vocab.stoi)

(0, 1, 116, collections.defaultdict)

In [0]:
TEXT.vocab.stoi['완전']

150

## 데이터 로더 설정

- 모델에게 배치 크기만큼 데이터를 전달하기 위한 수단

In [0]:
from torchtext.data import Iterator
import torch

In [0]:
# gpu 사용여부 설정
device = 'cuda' if torch.cuda.is_available()  else 'cpu'
device
# 여기서 바로 사용되지는 않고, 다음 단계에서 연결된다

'cpu'

In [0]:
dataLoader = Iterator( dataset    = dataset,
                       batch_size = 3,       # 설정값, 배치크기
                       device     = device   # gpu or cpu    
)

In [0]:
# 학습 ~ 
for batch in dataLoader:
  break

In [0]:
# 데이터 확인
batch


[torchtext.data.batch.Batch of size 3]
	[.id]:[torch.LongTensor of size 3]
	[.text]:[torch.LongTensor of size 3x42]
	[.label]:[torch.LongTensor of size 3]

In [0]:
batch.text

tensor([[   74,    74,    67,   555,    19,  1386,    19,  4464,   276,   775,
           112,   157,    67,    10,   231,    40,    15,    58,   309,     5,
           141,   185,    19,   190,  1627,   259,  2646,  2219,   170,    24,
            42,    67,     5,   103,     4,   259,     3,   114,    28,    52,
           219, 18976],
        [ 4308,     3,   617,  8987,  3367,     3,   617,    46,    12,    72,
            59,  2196,    14,     8,     7,    24,   148,    72,     3,    20,
            29,    79,   151,    12,   147,    20,     3,    15,    55,   155,
            27,    78,    71,     1,     1,     1,     1,     1,     1,     1,
             1,     1],
        [   41,   119,     6,    77,   162,    14,    34,   435,   515,  1214,
             2,    17,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
    